### ISSUE TITLE
How to load data

### ISSUE THREAD

**Issue by SolarWindRider** [AGENDD/RWKV-ASR#1]
Would you push sample data [temp_datasets] as coded in demo-state-tuning.sh to clarify how to load data? Thanks!

**Comment by jiamingkong** [comment]
Sure, thank you for your interest in this git. I believe the confusion was that the temp_datasets mentioned in our training script. It was the same as the librispeech on Huggingface, for training efficiency we pre-downloaded it on disk and did a bit of data conversion / cleaning. 

We are working on cleaning up the codes to enable the following possibilities:

- load a standard dataset from huggingface hub
- infer with pretrained model on a single audio input

The code should be updated this weekend, stay tuned!

**Comment by SolarWindRider** [comment]
I see what the matter is. In line 31 of demo-state-tuning.sh, the value of OP should be ["train", "eval"] rather [1,2,3]. That's why the script don't load dataset automatically.
